// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

#include <mach/kmod.h>

extern kern_return_t PC711Probe_kern_start(kmod_info_t *info, void *data);
extern kern_return_t PC711Probe_kern_stop(kmod_info_t *info, void *data);
extern kern_return_t _start(kmod_info_t *info, void *data);
extern kern_return_t _stop(kmod_info_t *info, void *data);

/*
 * Match the module glue generated by Xcode's kernel-extension target:
 * libkmod's _start/_stop wrappers remain the kmod entry points, while the
 * Lilu plugin entry points are exposed through _realmain/_antimain.
 *
 * Pointing kmod_info directly at PC711Probe_kern_start bypasses libkmod's
 * setup (including OSKextGetCurrentIdentifier) and can leave the IOKit
 * personality unable to instantiate.
 */
KMOD_EXPLICIT_DECL(com.stationk9.driver.PC711Probe, "1.2.0", _start, _stop)

kmod_start_func_t *_realmain = PC711Probe_kern_start;
kmod_stop_func_t *_antimain = PC711Probe_kern_stop;
